### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by alexellis** [swarm2k/swarm2k#64]
Swarm Cluster Data collected from /var/lib/docker/swarm/

https://objects-us-west-1.dream.io/swarm2k/swarm2k_swarm_mg0.tar.gz

**Comment by fsoppelsa** [comment]
@chanwit can you take a look?

**Comment by chanwit** [comment]
Oh sorry about that. Slipped to make it's public.
Should be working now.

@alexellis @fsoppelsa could you please try again?

**Comment by thaJeztah** [comment]
@chanwit works for me now, thanks!
